apiVersion: v1
kind: Service
metadata:
  name: {{ include "php-fpm.fullname" . }}
  labels:
    {{- include "php-fpm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: tcp-php
      protocol: TCP
      name: tcp-php
  selector:
    {{- include "php-fpm.selectorLabels" . | nindent 4 }}
