apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "phpkube.fullname" . }}-scripts
data:
  {{- range $path, $_ :=  .Files.Glob  "scripts/*.sh" }}
  {{- tpl (($.Files.Glob $path).AsConfig) $ | nindent 2  }}  
  {{- end }}