apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "phpkube.fullname" . }}-scripts
  labels:
    {{- include "phpkube.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
data:
  {{- range $path, $_ :=  .Files.Glob  "scripts/*.sh" }}
  {{- tpl (($.Files.Glob $path).AsConfig) $ | nindent 2  }}  
  {{- end }}