apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "phpkube.fullname" . }}-gitclone-sh
  labels:
    {{- include "phpkube.labels" . | nindent 4 }}
data:
  gitclone.sh: |-
    #!/bin/sh

    echo "gitclone starting"
    pwd
    ls -hls
    echo "creating directories"
    mkdir -p html
    mkdir -p log
    mkdir -p run
    mkdir -p temp/src
    mkdir -p var
    echo "change directory"
    cd temp/src

    git clone {{ .Values.git.url }} .
    git checkout {{ .Values.git.branch }}
    cd ../../
    ls -hlsa temp/src/
    cp -urf temp/src/* html/
    ls -hlsa html/
    echo "change permissions"
    chmod -Rf 750 html
    chown -Rf 1000:1000 .
    echo "remove source directory"
    rm -rf temp/src
