apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "phpkube.fullname" . }}-pre
  labels:
    {{- include "phpkube.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ttlSecondsAfterFinished: 30
  backoffLimit: 4
  template:
    metadata:
      annotations:
        checksum/gitclone: {{ include "phpkube.gitcloneCmSha" . }}
        checksum/scripts: {{ include "phpkube.cmSha" . }}
        checksum/env: {{ include "phpkube.envSha" . }}
    spec:
      initContainers:
      - name: gitclone
        image: alpine/git
        workingDir: "/home/"
        command: ["/bin/sh"]
        args: ["-c", "/home/gitclone.sh"]
        volumeMounts:
            - name: phpkube-data
              mountPath: "/home/"
            - name: gitclone-sh
              mountPath: "/home/gitclone.sh"
              subPath: "gitclone.sh"              
      containers:  
      - name: default
        image: busybox
        command: [ "/bin/sh", "-c", "echo Hello PHPKube"]
      {{- if .Values.jobs.composer }}
      - name: composer
        image: composer
        workingDir: "/home/html"
        command: ["/bin/sh", "-c", "/home/html/composer.sh"]
        volumeMounts:
            - name: phpkube-data
              mountPath: "/home/"
            - name: scripts
              mountPath: "/home/html/composer.sh"
              subPath: "composer.sh"
      {{- end -}}
      {{- if .Values.jobs.npm }}
      - name: npm
        image: node
        workingDir: "/home/html"
        command: ["/bin/sh", "-c", "/home/html/npm.sh"]
        volumeMounts:
            - name: phpkube-data
              mountPath: "/home/"
            - name: scripts
              mountPath: "/home/html/npm.sh"
              subPath: "npm.sh"
      {{- end }}
      restartPolicy: Never
      volumes:
      - name: phpkube-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name -}}-data
      - name: gitclone-sh
        configMap: 
          defaultMode: 0555
          name: {{ include "phpkube.fullname" . }}-gitclone-sh
      - name: scripts
        configMap:
          defaultMode: 0555 
          name: {{ include "phpkube.fullname" . }}-scripts