apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name -}}-data
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteMany
  {{ if .Values.persistentVolume.storageClassName  }}
  storageClassName: {{ .Values.persistentVolume.storageClassName | quote }}
  {{ end }}