apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nginx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/default-conf: {{ include (print $.Template.BasePath "/default-cm.yaml") . | sha256sum }}
        checksum/nginx-conf: {{ include (print $.Template.BasePath "/nginx-cm.yaml") . | sha256sum }}
        checksum/gitclone: {{ include "phpkube.gitcloneCmSha" . }}
        checksum/scripts: {{ include "phpkube.cmSha" . }}
        checksum/env: {{ include "phpkube.envSha" . }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "nginx.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: phpkube-data
              mountPath: "/home/phpkube"
            - name: default-conf
              mountPath: "/etc/nginx/conf.d/default.conf"
              subPath: "default.conf"
            - name: nginx-conf
              mountPath: "/etc/nginx/nginx.conf"
              subPath: "nginx.conf"
          livenessProbe:
            httpGet:
              path: /nginx_status
              port: http
          readinessProbe:
            httpGet:
              path: /nginx_status
              port: http
            initialDelaySeconds: 30
            failureThreshold: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: phpkube-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name -}}-data
      - name: default-conf
        configMap:
          name: {{ include "nginx.fullname" . }}-default-conf
      - name: nginx-conf
        configMap:
          name: {{ include "nginx.fullname" . }}-nginx-conf
